### ISSUE TITLE
When adding custom language url, tri18n will add a slash before the lang param

### ISSUE THREAD

**Issue by alinturbut** [Stiudeo/tri18n#1]
This is the configuration we have:

``` 
tri18n
    .configure({
      lang: langCode || config.language,
      cache: false,
      url: "${config.apiUrl}/${config.langData}",
      parse: (data) => {
        return data.configuration;
      },
      raw: true
    });
```

Url being called: /api/v1/translations?language=/en_GB.json

Bug in code: https://github.com/Stiudeo/tri18n/blob/master/src/util.js#L49

Basically line 49 should be removed or added after adding the url parameters. 

Will try a PR if time is good with me :)

**Comment by snupa** [comment]
Updated the util function to use the raw config.url when the CONFIG.parse() function is given.This is to ensure backward-compatibility with other projects.
Published version 1.0.5
